---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: Cleanup trailing whitespaces
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ansible-doctor
        name: Generate README.md with ansible-doctor
        entry: uv run ansible-doctor
        language: system
        pass_filenames: false
        files: ^(defaults/|meta/|HEADER\.md|\.ansibledoctor\.yml)
        stages: [pre-commit]
      - id: ansible-lint
        name: Run ansible-lint
        entry: uv run ansible-lint
        language: system
        types: [yaml]
        stages: [pre-commit]
      - id: yamllint
        name: Run yamllint
        entry: uv run yamllint
        language: system
        types: [yaml]
        stages: [pre-commit]
