[project]
name = "template-ansible-role"
version = "0.1.0"
description = "A template for creating Ansible roles"
readme = "README.md"
requires-python = ">=3.12,<3.15"

[dependency-groups]
dev = [
    "ansible-core>=2.18",
    "ansible-dev-tools",
    "ansible-doctor",
    "prek",
    "molecule",
    "molecule-plugins[podman]",
]
openstack = [
    "openstacksdk",
    "molecule-plugins[openstack]",
]
