---
name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "template-ansible-role"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: "template-ansible-role"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: pip install -q yamllint

      - name: Run tests
        run: yamllint .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - "debian:12"
          - "rockylinux:9"
          - "ubuntu:24.04"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: "template-ansible-role"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: pip install ansible molecule molecule-plugins[docker] docker

      - name: Run tests
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
